### ISSUE TITLE
Usage example in readme please... 

### ISSUE THREAD

**Issue by wxguy** [cagix/pandoc-thesis#1]
Very good project. You have put in lot of effort to create and maintain this project but usage example along with some example output documents (PDF) would provide lot of visibility.

**Comment by cagix** [comment]
@wxguy well, there is already a usage example, right under "Usage" in https://github.com/cagix/pandoc-thesis/blob/master/README.md?

**Comment by wxguy** [comment]
Yes that's true. What I meant is the kind of documentation written in the Eisvogel templates project where you are active. I would like to see some PDF for different themes under example directory. On readme file you can mention the kind of variables your templates takes. That would be great. Believe me few output PDF in the project directory will be extremely useful if someone comes here for the first time. That will strait away help the user to imagine the way their documentation going to be.

**Comment by cagix** [comment]
i see your point. usually i try to avoid to commit generated artifacts, since it would increase the size of the repo ... however, in this case it might help potential users :)

**Comment by cagix** [comment]
@wxguy thanks for your suggestion!

**Comment by wxguy** [comment]
Very nice. Keep up the good work.
