### ISSUE TITLE
How to add more information to eisvogel title page

### ISSUE THREAD

**Issue by marius-mm** [cagix/pandoc-thesis#10]
How would I add more information like the institute to the titlepage?

**Comment by cagix** [comment]
closed by https://github.com/Wandmalfarbe/pandoc-latex-template/issues/255

**Comment by cagix** [comment]
@marius-mm You would have to modify the title page of Eisvogel (https://github.com/cagix/pandoc-thesis/blob/master/titlepage.tex, lines 885 to 960). If you use variables (see Pandoc templates: https://pandoc.org/MANUAL.html#templates, you can set them via the metadata, for example.  Alternatively, you can define your own title page, have a look at https://github.com/cagix/pandoc-thesis/blob/master/titlepage.tex.
