### ISSUE TITLE
Large gaps when hierarchy becomes too large ? 

### ISSUE THREAD

**Issue by genaray** [cagix/pandoc-thesis#33]
## Using
- Windows 11 UH22
- Docker 4.14.1
- WLS2 Ubuntu ( for making )

## Problem

I just noticed that there large gaps between headers when the hierarchy becomes too big...
This is only the case for larger hierarchys and sometimes may also appear when a paragraph gets too big and continues on the next page. 

This is a valid problem for all templates, `simple`, `cleanthesis` and `eisvogel`. I also tried different versions of them.
Is this a problem in general ? Or something that can be fixed easily ? 

![image](https://user-images.githubusercontent.com/20269164/205310510-f3cd8f20-f13a-4757-8139-9e46a3b4a63e.png)

## The .md file

```
# Technologien

## Sprachen

Während der Praxisphase wurden für die internen Projekte auf eine Vielzahl von verschiedenen Programmiersprachen zurückgegriffen, bei diesen handelt es sich vor allem um höhere Programmier und Scriptsprachen einige dieser werden hier  näher erläutert. [Verweis ?]

### Java

Java ist eine objektorientierte Programmiersprache, die im Jahre 1995 mit der ersten Version veröffentlicht wurde. 2010 wechselte sie den Besitzer und ist nun eine eingetragene Marke der Firma Oracle. Da Java zu Bytecode kompiliert wird, ist es möglich durch die Java Laufzeitumgebung und die eigene Virtuelle Maschine, diesen Bytecode auf jeder beliebigen Plattform auszuführen. Andere Programmiersprachen wie Groovy, Kotlin und Scala werden ebenfalls zu Java-Bytecode kompiliert um von der Platformunabhängikeit zu profitieren. 

### Kotlin
### Groovy
### C\#

## Frameworks
### Grails
### GRPC
### Hibernate
### OpenXR

## Hardware & Engines 
### Tooz
### Unity
### Hololens2
```

**Comment by cagix** [comment]
We use LaTeX as backend to do all the formatting work. LaTeX follows the established rules from book printing ...  I noticed that your mwe contains very little text and many headings. This, together with the rules that LaTeX has to follow when typesetting the document, could result in a lot of whitespace. 

Could you test a realistic text (in terms of volume) with the corresponding illustrations?

**Comment by genaray** [comment]
> We use LaTeX as backend to do all the formatting work. LaTeX follows the established rules from book printing ... I noticed that your mwe contains very little text and many headings. This, together with the rules that LaTeX has to follow when typesetting the document, could result in a lot of whitespace.
> 
> Could you test a realistic text (in terms of volume) with the corresponding illustrations?

Thanks ! That actually solved the issue, more Text and non empty paragraphs made it looks "normal" again ^^ Still a bit weird, never had that problem in overleaf which is also latex.
