### ISSUE TITLE
Probleme bei Pfäden mit Leerzeichen

### ISSUE THREAD

**Issue by Paddy369** [cagix/pandoc-thesis#57]
Wenn im Workdirectory Pfäde enthalten sind, in denen Leerzeichen vorkommen, dann schlägt der docker run Befehel leider fehl.

**Comment by cagix** [comment]
@Paddy369 Kannst Du mir bitte noch etwas mehr Kontext geben: Was genau hast Du gemacht, so dass es schief lief? Welches Betriebssystem ist involviert?

**Comment by Paddy369** [comment]
Ja danke, es funktioniert einwandfrei @cagix 👍
