### ISSUE TITLE
Wrong mountpath while using CygWin

### ISSUE THREAD

**Issue by AMatutat** [cagix/pandoc-thesis#6]
If you use CygWin for execution:
make will set the mountpath to
 ```
  /cygdrive/{PATH}
instead of 
  /{PATH}
 ```

Work around:
set absolute path in makefile

**Comment by cagix** [comment]
well, i could promote the `$(shell pwd)` (in the definition of the `PANDOC` variable) to a new variable and put a warning/comment in Readme and Makefile ...

**Comment by cagix** [comment]
promoted variable and added comments (783475ae2), use internal variable instead of starting a new shell to execute pwd (65dfce928) ... checked on linux and macos.

@AMatutat can you please check if this changes do work in a windows environment?

**Comment by cagix** [comment]
ok, closing this now. please feel free to reopen if there is anything left to do.
