### ISSUE TITLE
Sometimes empty pages between chapters

### ISSUE THREAD

**Issue by AMatutat** [cagix/pandoc-thesis#7]
Also creates empty Pages between abstract and acknowledgements and between acknowledgements and table of content. 

- using eisvogel
- using given structure

**Comment by cagix** [comment]
could you provide some mwe please?

may be it’s the book style: each chapter starts on a new right page, as the result is intended to be printed double sided :)

**Comment by AMatutat** [comment]
Just checked it, and yes it is the book style. 
Guess it's not a real problem than.

**Comment by cagix** [comment]
ack. 

do you feel this needs to be documented somewhere?

**Comment by AMatutat** [comment]
A little note would be nice.

**Comment by cagix** [comment]
ok, will be done ...

**Comment by cagix** [comment]
#3f76da3f8856b should fix this
