### ISSUE TITLE
Bibliography has no own header

### ISSUE THREAD

**Issue by AMatutat** [cagix/pandoc-thesis#8]
It copies the header from the last chapter. 
![Example](https://user-images.githubusercontent.com/32962412/73383411-91c9c280-42c9-11ea-8352-3061536cae10.PNG)

**Comment by cagix** [comment]
can you provide a mwe, please?

**Comment by cagix** [comment]
is there no (section) header at all (i.e. is there no unumbered header like „literatur“ or „references“ right in front of the bibliography?) or is it just the page header?

**Comment by AMatutat** [comment]
There is a unumbered section header

[mwe.zip](https://github.com/cagix/pandoc-thesis/files/4130008/mwe.zip)

**Comment by AMatutat** [comment]
There is a unnumbered section header but it takes the last numbered section header for the page header

[mwe.zip](https://github.com/cagix/pandoc-thesis/files/4130021/mwe.zip)

**Comment by cagix** [comment]
confirmed.

at first it seemed to me an issue with fancyheaders. however, the reported behaviour can be observed with „simple“ and „cleanthesis“, which both do not use fancyheaders ...

maybe its connected to the scrbook class. when re-defining leftmark and rightmark to „literatur“ just after the unnumbered section header „literatur“ it will use the correct page heading. => quickfix

however, i‘m not quite sure, if it’s the proper way. more digging needed.

**Comment by cagix** [comment]
should be fixed with 62c105af0632e5

@AMatutat please verify. in case this is not resolved for you, please feel free to reopen.

**Comment by AMatutat** [comment]
problem is fixed
