### ISSUE TITLE
numbering equations ? 

### ISSUE THREAD

**Issue by marius-mm** [cagix/pandoc-thesis#9]
Is there a way to create numbering for equations created with $$ like $$ X $$ for example ?

**Comment by marius-mm** [comment]
I installed the pandoc-xnos filters. 
[pandoc-xnos](https://github.com/tomduck/pandoc-xnos)

**Comment by cagix** [comment]
@marius-mm  Yup, that's the way. You could also simply use plain latex commands, as pdflatex is used in the backend.

**Comment by marius-mm** [comment]
jeah just saw using 
$$
X
$$
leads to numbering
